"""Management command to seed initial categories and prompts."""
from django.core.management.base import BaseCommand
from game.models import Category, Prompt


SEED_CATEGORIES = [
    {
        'name': 'Classic Egyptian Movies',
        'name_ar': 'أفلام مصرية كلاسيكية',
        'genre': 'movies',
        'sub_genre': 'egyptian',
        'difficulty': 'medium',
        'icon': '🎬',
        'prompts': [
            {'title': 'The Yacoubian Building', 'title_ar': 'عمارة يعقوبيان', 'difficulty': 2},
            {'title': 'The Nightingale\'s Prayer', 'title_ar': 'دعاء الكروان', 'difficulty': 3},
            {'title': 'Cairo Station', 'title_ar': 'باب الحديد', 'difficulty': 3},
            {'title': 'The Mummy', 'title_ar': 'المومياء', 'difficulty': 2},
            {'title': 'Ismailia Rayeh Gay', 'title_ar': 'إسماعيلية رايح جاي', 'difficulty': 1},
            {'title': 'Al Limby', 'title_ar': 'اللمبي', 'difficulty': 1},
            {'title': 'Asal Eswed', 'title_ar': 'عسل أسود', 'difficulty': 2},
            {'title': 'Morgan Ahmed Morgan', 'title_ar': 'مرجان أحمد مرجان', 'difficulty': 2},
            {'title': 'The Island', 'title_ar': 'الجزيرة', 'difficulty': 2},
            {'title': 'Saidi in the American University', 'title_ar': 'صعيدي في الجامعة الأمريكية', 'difficulty': 1},
            {'title': 'Mafia', 'title_ar': 'مافيا', 'difficulty': 2},
            {'title': 'Tito', 'title_ar': 'تيتو', 'difficulty': 2},
            {'title': 'Ehky Ya Shahrazad', 'title_ar': 'احكي يا شهرزاد', 'difficulty': 3},
            {'title': 'The Blue Elephant', 'title_ar': 'الفيل الأزرق', 'difficulty': 2},
            {'title': 'Welad Rizk', 'title_ar': 'ولاد رزق', 'difficulty': 1},
            {'title': 'Keda Reda', 'title_ar': 'كدة رضا', 'difficulty': 2},
            {'title': 'Zarf Tarek', 'title_ar': 'ظرف طارق', 'difficulty': 2},
            {'title': 'Hammam in Amsterdam', 'title_ar': 'حمام في أمستردام', 'difficulty': 1},
            {'title': 'El Nazer', 'title_ar': 'الناظر', 'difficulty': 1},
            {'title': 'Ramadan Mabrouk', 'title_ar': 'رمضان مبروك أبو العلمين حمودة', 'difficulty': 2},
        ],
    },
    {
        'name': 'Hollywood Movies 2000-2020',
        'name_ar': 'أفلام هوليوود ٢٠٠٠-٢٠٢٠',
        'genre': 'movies',
        'sub_genre': 'hollywood',
        'difficulty': 'easy',
        'icon': '🎥',
        'prompts': [
            {'title': 'Titanic', 'title_ar': 'تايتانيك', 'difficulty': 1},
            {'title': 'The Dark Knight', 'title_ar': 'فارس الظلام', 'difficulty': 2},
            {'title': 'Inception', 'title_ar': 'استهلال', 'difficulty': 2},
            {'title': 'Avatar', 'title_ar': 'أفاتار', 'difficulty': 1},
            {'title': 'The Avengers', 'title_ar': 'المنتقمون', 'difficulty': 1},
            {'title': 'Frozen', 'title_ar': 'ملكة الثلج', 'difficulty': 1},
            {'title': 'Harry Potter', 'title_ar': 'هاري بوتر', 'difficulty': 1},
            {'title': 'Spider-Man', 'title_ar': 'سبايدرمان', 'difficulty': 1},
            {'title': 'The Lion King', 'title_ar': 'الأسد الملك', 'difficulty': 1},
            {'title': 'Pirates of the Caribbean', 'title_ar': 'قراصنة الكاريبي', 'difficulty': 1},
            {'title': 'Fast & Furious', 'title_ar': 'سريع وغاضب', 'difficulty': 1},
            {'title': 'Jurassic World', 'title_ar': 'عالم الديناصورات', 'difficulty': 1},
            {'title': 'Iron Man', 'title_ar': 'الرجل الحديدي', 'difficulty': 1},
            {'title': 'The Matrix', 'title_ar': 'ماتريكس', 'difficulty': 2},
            {'title': 'Gladiator', 'title_ar': 'المصارع', 'difficulty': 2},
            {'title': 'Shrek', 'title_ar': 'شريك', 'difficulty': 1},
            {'title': 'Finding Nemo', 'title_ar': 'البحث عن نيمو', 'difficulty': 1},
            {'title': 'Joker', 'title_ar': 'جوكر', 'difficulty': 2},
            {'title': 'Black Panther', 'title_ar': 'النمر الأسود', 'difficulty': 1},
            {'title': 'Interstellar', 'title_ar': 'بين النجوم', 'difficulty': 3},
        ],
    },
    {
        'name': 'Bollywood Stars',
        'name_ar': 'نجوم بوليوود',
        'genre': 'actors',
        'sub_genre': 'bollywood',
        'difficulty': 'medium',
        'icon': '⭐',
        'prompts': [
            {'title': 'Shah Rukh Khan', 'title_ar': 'شاروخان', 'difficulty': 1},
            {'title': 'Amitabh Bachchan', 'title_ar': 'أميتاب باتشان', 'difficulty': 2},
            {'title': 'Salman Khan', 'title_ar': 'سلمان خان', 'difficulty': 1},
            {'title': 'Aamir Khan', 'title_ar': 'عامر خان', 'difficulty': 2},
            {'title': 'Priyanka Chopra', 'title_ar': 'بريانكا شوبرا', 'difficulty': 2},
            {'title': 'Deepika Padukone', 'title_ar': 'ديبيكا بادوكون', 'difficulty': 2},
            {'title': 'Hrithik Roshan', 'title_ar': 'ريتيك روشان', 'difficulty': 2},
            {'title': 'Aishwarya Rai', 'title_ar': 'آيشواريا راي', 'difficulty': 2},
            {'title': 'Ranveer Singh', 'title_ar': 'رانفير سينغ', 'difficulty': 3},
            {'title': 'Katrina Kaif', 'title_ar': 'كاترينا كيف', 'difficulty': 2},
            {'title': 'Akshay Kumar', 'title_ar': 'أكشاي كومار', 'difficulty': 2},
            {'title': 'Kareena Kapoor', 'title_ar': 'كارينا كابور', 'difficulty': 2},
            {'title': 'Ranbir Kapoor', 'title_ar': 'رانبير كابور', 'difficulty': 3},
            {'title': 'Alia Bhatt', 'title_ar': 'عليا بهات', 'difficulty': 3},
            {'title': 'Varun Dhawan', 'title_ar': 'فارون دهاوان', 'difficulty': 3},
            {'title': 'Madhuri Dixit', 'title_ar': 'مادهوري ديكسيت', 'difficulty': 3},
            {'title': 'Kajol', 'title_ar': 'كاجول', 'difficulty': 2},
            {'title': 'Tiger Shroff', 'title_ar': 'تايغر شروف', 'difficulty': 3},
            {'title': 'Shahid Kapoor', 'title_ar': 'شاهد كابور', 'difficulty': 3},
            {'title': 'Anushka Sharma', 'title_ar': 'أنوشكا شارما', 'difficulty': 3},
        ],
    },
    {
        'name': 'Syrian TV Shows',
        'name_ar': 'مسلسلات سورية',
        'genre': 'tv_shows',
        'sub_genre': 'syrian',
        'difficulty': 'medium',
        'icon': '📺',
        'prompts': [
            {'title': 'Bab Al-Hara', 'title_ar': 'باب الحارة', 'difficulty': 1},
            {'title': 'Spotlight', 'title_ar': 'بقعة ضوء', 'difficulty': 1},
            {'title': 'Al-Ijtiyah', 'title_ar': 'الاجتياح', 'difficulty': 3},
            {'title': 'Maraya', 'title_ar': 'مرايا', 'difficulty': 2},
            {'title': 'Ghawwar', 'title_ar': 'غوار الطوشة', 'difficulty': 1},
            {'title': 'Al-Wilada Min Al-Khasira', 'title_ar': 'الولادة من الخاصرة', 'difficulty': 3},
            {'title': 'Sabaya', 'title_ar': 'صبايا', 'difficulty': 2},
            {'title': 'Hammam Al-Qishani', 'title_ar': 'حمام القيشاني', 'difficulty': 2},
            {'title': 'Ahlam Al-Madina', 'title_ar': 'أحلام المدينة', 'difficulty': 3},
            {'title': 'Zaman Al-Wasl', 'title_ar': 'زمن الوصل', 'difficulty': 3},
            {'title': 'Al-Hayba', 'title_ar': 'الهيبة', 'difficulty': 1},
            {'title': 'Cello', 'title_ar': 'تشيللو', 'difficulty': 3},
            {'title': 'Al-Taghriba Al-Filistiniya', 'title_ar': 'التغريبة الفلسطينية', 'difficulty': 2},
            {'title': 'Ahl Al-Gharam', 'title_ar': 'أهل الغرام', 'difficulty': 2},
            {'title': 'Dayaa Dayaa', 'title_ar': 'ضيعة ضايعة', 'difficulty': 1},
            {'title': 'Buqa\'at Daw\'', 'title_ar': 'بقعة ضوء', 'difficulty': 2},
            {'title': 'Al-Kharbeh', 'title_ar': 'الخربة', 'difficulty': 2},
            {'title': 'Nisa\' Min Hadha Al-Zaman', 'title_ar': 'نساء من هذا الزمان', 'difficulty': 3},
            {'title': 'Al-Faseel', 'title_ar': 'الفصيل', 'difficulty': 3},
            {'title': 'Ghadan Naltaqi', 'title_ar': 'غداً نلتقي', 'difficulty': 3},
        ],
    },
    {
        'name': 'Anime Characters',
        'name_ar': 'شخصيات أنمي',
        'genre': 'anime',
        'sub_genre': '',
        'difficulty': 'easy',
        'icon': '🎌',
        'prompts': [
            {'title': 'Naruto', 'title_ar': 'ناروتو', 'difficulty': 1},
            {'title': 'Goku (Dragon Ball)', 'title_ar': 'غوكو', 'difficulty': 1},
            {'title': 'Luffy (One Piece)', 'title_ar': 'لوفي', 'difficulty': 1},
            {'title': 'Conan (Detective Conan)', 'title_ar': 'كونان', 'difficulty': 1},
            {'title': 'Captain Tsubasa', 'title_ar': 'الكابتن ماجد', 'difficulty': 1},
            {'title': 'Pikachu (Pokemon)', 'title_ar': 'بيكاتشو', 'difficulty': 1},
            {'title': 'Sailor Moon', 'title_ar': 'سيلر مون', 'difficulty': 1},
            {'title': 'Eren (Attack on Titan)', 'title_ar': 'إيرين', 'difficulty': 2},
            {'title': 'Light Yagami (Death Note)', 'title_ar': 'لايت ياغامي', 'difficulty': 2},
            {'title': 'Sasuke (Naruto)', 'title_ar': 'ساسكي', 'difficulty': 1},
            {'title': 'Vegeta (Dragon Ball)', 'title_ar': 'فيجيتا', 'difficulty': 2},
            {'title': 'Zoro (One Piece)', 'title_ar': 'زورو', 'difficulty': 2},
            {'title': 'Gon (Hunter x Hunter)', 'title_ar': 'غون', 'difficulty': 2},
            {'title': 'Saitama (One Punch Man)', 'title_ar': 'سايتاما', 'difficulty': 2},
            {'title': 'Tanjiro (Demon Slayer)', 'title_ar': 'تانجيرو', 'difficulty': 2},
            {'title': 'Levi (Attack on Titan)', 'title_ar': 'ليفاي', 'difficulty': 2},
            {'title': 'Itachi (Naruto)', 'title_ar': 'إيتاشي', 'difficulty': 2},
            {'title': 'Genos (One Punch Man)', 'title_ar': 'جينوس', 'difficulty': 3},
            {'title': 'Totoro (My Neighbor Totoro)', 'title_ar': 'توتورو', 'difficulty': 2},
            {'title': 'Astro Boy', 'title_ar': 'أسترو بوي', 'difficulty': 2},
        ],
    },
    {
        'name': 'Football Legends',
        'name_ar': 'أساطير كرة القدم',
        'genre': 'sports',
        'sub_genre': '',
        'difficulty': 'easy',
        'icon': '⚽',
        'prompts': [
            {'title': 'Lionel Messi', 'title_ar': 'ليونيل ميسي', 'difficulty': 1},
            {'title': 'Cristiano Ronaldo', 'title_ar': 'كريستيانو رونالدو', 'difficulty': 1},
            {'title': 'Mohamed Salah', 'title_ar': 'محمد صلاح', 'difficulty': 1},
            {'title': 'Neymar Jr', 'title_ar': 'نيمار', 'difficulty': 1},
            {'title': 'Zinedine Zidane', 'title_ar': 'زين الدين زيدان', 'difficulty': 1},
            {'title': 'Ronaldinho', 'title_ar': 'رونالدينيو', 'difficulty': 1},
            {'title': 'Maradona', 'title_ar': 'مارادونا', 'difficulty': 1},
            {'title': 'Pelé', 'title_ar': 'بيليه', 'difficulty': 1},
            {'title': 'Kylian Mbappé', 'title_ar': 'كيليان مبابي', 'difficulty': 1},
            {'title': 'Karim Benzema', 'title_ar': 'كريم بنزيما', 'difficulty': 1},
            {'title': 'Robert Lewandowski', 'title_ar': 'روبرت ليفاندوفسكي', 'difficulty': 2},
            {'title': 'Erling Haaland', 'title_ar': 'إيرلينغ هالاند', 'difficulty': 2},
            {'title': 'Luka Modrić', 'title_ar': 'لوكا مودريتش', 'difficulty': 2},
            {'title': 'Sadio Mané', 'title_ar': 'ساديو ماني', 'difficulty': 2},
            {'title': 'Riyad Mahrez', 'title_ar': 'رياض محرز', 'difficulty': 2},
            {'title': 'David Beckham', 'title_ar': 'ديفيد بيكهام', 'difficulty': 1},
            {'title': 'Thierry Henry', 'title_ar': 'تييري هنري', 'difficulty': 2},
            {'title': 'Ronaldo Nazário', 'title_ar': 'رونالدو البرازيلي', 'difficulty': 2},
            {'title': 'Zlatan Ibrahimović', 'title_ar': 'زلاتان إبراهيموفيتش', 'difficulty': 2},
            {'title': 'Gianluigi Buffon', 'title_ar': 'جيانلويجي بوفون', 'difficulty': 3},
        ],
    },
    {
        'name': 'Ramadan Series',
        'name_ar': 'مسلسلات رمضان',
        'genre': 'tv_shows',
        'sub_genre': 'egyptian',
        'difficulty': 'easy',
        'icon': '🌙',
        'prompts': [
            {'title': 'Al-Kebeer Awi', 'title_ar': 'الكبير أوي', 'difficulty': 1},
            {'title': 'Layali El-Helmiya', 'title_ar': 'ليالي الحلمية', 'difficulty': 2},
            {'title': 'Raafat El-Haggan', 'title_ar': 'رأفت الهجان', 'difficulty': 2},
            {'title': 'Zat', 'title_ar': 'ذات', 'difficulty': 3},
            {'title': 'El-Gamaa', 'title_ar': 'الجماعة', 'difficulty': 3},
            {'title': 'Niran Sadiqa', 'title_ar': 'نيران صديقة', 'difficulty': 2},
            {'title': 'Tamer wa Shawqiya', 'title_ar': 'تامر وشوقية', 'difficulty': 1},
            {'title': 'Fein Aqlak', 'title_ar': 'فين عقلك', 'difficulty': 2},
            {'title': 'El-Nehaya', 'title_ar': 'النهاية', 'difficulty': 2},
            {'title': 'Paranormal', 'title_ar': 'ما وراء الطبيعة', 'difficulty': 2},
            {'title': 'Newton\'s Cradle', 'title_ar': 'كفر دلهاب', 'difficulty': 3},
            {'title': 'Grand Hotel', 'title_ar': 'جراند أوتيل', 'difficulty': 2},
            {'title': 'Taht El-Saytara', 'title_ar': 'تحت السيطرة', 'difficulty': 2},
            {'title': 'Hekayat Banat', 'title_ar': 'حكايات بنات', 'difficulty': 2},
            {'title': 'La Casa de Papel (Arabic)', 'title_ar': 'لا كاسا دي بابيل', 'difficulty': 2},
            {'title': 'Suits (Arabic)', 'title_ar': 'سوتس بالعربي', 'difficulty': 2},
            {'title': 'El-Prince', 'title_ar': 'البرنس', 'difficulty': 1},
            {'title': 'El-Ekhteyar', 'title_ar': 'الاختيار', 'difficulty': 1},
            {'title': 'Fathy Iskandarany', 'title_ar': 'فتحي إسكندراني', 'difficulty': 2},
            {'title': 'Kalabsh', 'title_ar': 'كلبش', 'difficulty': 1},
        ],
    },
    {
        'name': 'Marvel / DC Heroes',
        'name_ar': 'أبطال مارفل / دي سي',
        'genre': 'movies',
        'sub_genre': 'hollywood',
        'difficulty': 'easy',
        'icon': '🦸',
        'prompts': [
            {'title': 'Spider-Man', 'title_ar': 'سبايدرمان', 'difficulty': 1},
            {'title': 'Batman', 'title_ar': 'باتمان', 'difficulty': 1},
            {'title': 'Superman', 'title_ar': 'سوبرمان', 'difficulty': 1},
            {'title': 'Iron Man', 'title_ar': 'الرجل الحديدي', 'difficulty': 1},
            {'title': 'Captain America', 'title_ar': 'كابتن أمريكا', 'difficulty': 1},
            {'title': 'Thor', 'title_ar': 'ثور', 'difficulty': 1},
            {'title': 'Hulk', 'title_ar': 'هالك', 'difficulty': 1},
            {'title': 'Wonder Woman', 'title_ar': 'المرأة الخارقة', 'difficulty': 1},
            {'title': 'Black Widow', 'title_ar': 'الأرملة السوداء', 'difficulty': 2},
            {'title': 'Thanos', 'title_ar': 'ثانوس', 'difficulty': 2},
            {'title': 'Wolverine', 'title_ar': 'ولفرين', 'difficulty': 1},
            {'title': 'Deadpool', 'title_ar': 'ديدبول', 'difficulty': 1},
            {'title': 'Doctor Strange', 'title_ar': 'دكتور سترينج', 'difficulty': 2},
            {'title': 'Black Panther', 'title_ar': 'النمر الأسود', 'difficulty': 1},
            {'title': 'The Flash', 'title_ar': 'فلاش', 'difficulty': 1},
            {'title': 'Aquaman', 'title_ar': 'أكوامان', 'difficulty': 1},
            {'title': 'Joker', 'title_ar': 'الجوكر', 'difficulty': 1},
            {'title': 'Harley Quinn', 'title_ar': 'هارلي كوين', 'difficulty': 2},
            {'title': 'Loki', 'title_ar': 'لوكي', 'difficulty': 2},
            {'title': 'Groot', 'title_ar': 'غروت', 'difficulty': 2},
        ],
    },
    {
        'name': 'Arab Celebrities',
        'name_ar': 'مشاهير عرب',
        'genre': 'celebrities',
        'sub_genre': 'arab',
        'difficulty': 'easy',
        'icon': '🌟',
        'prompts': [
            {'title': 'Adel Imam', 'title_ar': 'عادل إمام', 'difficulty': 1},
            {'title': 'Ahmed Helmy', 'title_ar': 'أحمد حلمي', 'difficulty': 1},
            {'title': 'Mohamed Ramadan', 'title_ar': 'محمد رمضان', 'difficulty': 1},
            {'title': 'Amr Diab', 'title_ar': 'عمرو دياب', 'difficulty': 1},
            {'title': 'Nancy Ajram', 'title_ar': 'نانسي عجرم', 'difficulty': 1},
            {'title': 'Fairuz', 'title_ar': 'فيروز', 'difficulty': 1},
            {'title': 'Umm Kulthum', 'title_ar': 'أم كلثوم', 'difficulty': 1},
            {'title': 'Tamer Hosny', 'title_ar': 'تامر حسني', 'difficulty': 1},
            {'title': 'Haifa Wehbe', 'title_ar': 'هيفاء وهبي', 'difficulty': 1},
            {'title': 'Elissa', 'title_ar': 'إليسا', 'difficulty': 1},
            {'title': 'Kadim Al Sahir', 'title_ar': 'كاظم الساهر', 'difficulty': 2},
            {'title': 'Yousra', 'title_ar': 'يسرا', 'difficulty': 2},
            {'title': 'Ahmed Mekky', 'title_ar': 'أحمد مكي', 'difficulty': 1},
            {'title': 'Mona Zaki', 'title_ar': 'منى زكي', 'difficulty': 2},
            {'title': 'Karim Abdel Aziz', 'title_ar': 'كريم عبد العزيز', 'difficulty': 2},
            {'title': 'Assala Nasri', 'title_ar': 'أصالة نصري', 'difficulty': 2},
            {'title': 'Ragheb Alama', 'title_ar': 'راغب علامة', 'difficulty': 2},
            {'title': 'Wael Kfoury', 'title_ar': 'وائل كفوري', 'difficulty': 2},
            {'title': 'Sherine Abdel Wahab', 'title_ar': 'شيرين عبد الوهاب', 'difficulty': 1},
            {'title': 'Mohamed Henedy', 'title_ar': 'محمد هنيدي', 'difficulty': 1},
        ],
    },
    {
        'name': 'Video Game Characters',
        'name_ar': 'شخصيات ألعاب فيديو',
        'genre': 'video_games',
        'sub_genre': '',
        'difficulty': 'easy',
        'icon': '🎮',
        'prompts': [
            {'title': 'Mario', 'title_ar': 'ماريو', 'difficulty': 1},
            {'title': 'Sonic the Hedgehog', 'title_ar': 'سونيك', 'difficulty': 1},
            {'title': 'Pikachu', 'title_ar': 'بيكاتشو', 'difficulty': 1},
            {'title': 'Link (Zelda)', 'title_ar': 'لينك', 'difficulty': 2},
            {'title': 'Pac-Man', 'title_ar': 'باك مان', 'difficulty': 1},
            {'title': 'Minecraft Steve', 'title_ar': 'ستيف ماينكرافت', 'difficulty': 1},
            {'title': 'Kratos (God of War)', 'title_ar': 'كريتوس', 'difficulty': 2},
            {'title': 'Master Chief (Halo)', 'title_ar': 'ماستر تشيف', 'difficulty': 2},
            {'title': 'Lara Croft', 'title_ar': 'لارا كروفت', 'difficulty': 2},
            {'title': 'Crash Bandicoot', 'title_ar': 'كراش', 'difficulty': 1},
            {'title': 'Donkey Kong', 'title_ar': 'دونكي كونغ', 'difficulty': 1},
            {'title': 'Mega Man', 'title_ar': 'ميغا مان', 'difficulty': 2},
            {'title': 'Ryu (Street Fighter)', 'title_ar': 'ريو', 'difficulty': 2},
            {'title': 'Cloud (Final Fantasy)', 'title_ar': 'كلاود', 'difficulty': 3},
            {'title': 'Ezio (Assassin\'s Creed)', 'title_ar': 'إيزيو', 'difficulty': 2},
            {'title': 'Arthur Morgan (RDR2)', 'title_ar': 'آرثر مورغان', 'difficulty': 3},
            {'title': 'Geralt (The Witcher)', 'title_ar': 'جيرالت', 'difficulty': 3},
            {'title': 'Among Us Crewmate', 'title_ar': 'أمونغ أس', 'difficulty': 1},
            {'title': 'Fortnite Default Skin', 'title_ar': 'فورتنايت', 'difficulty': 1},
            {'title': 'GTA Trevor', 'title_ar': 'تريفور', 'difficulty': 2},
        ],
    },
]


class Command(BaseCommand):
    help = 'Seed initial categories and prompts for 001 Game'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Clear existing data before seeding')

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write('Clearing existing data...')
            Prompt.objects.all().delete()
            Category.objects.all().delete()

        total_categories = 0
        total_prompts = 0

        for cat_data in SEED_CATEGORIES:
            prompts_data = cat_data.pop('prompts')

            category, created = Category.objects.get_or_create(
                name=cat_data['name'],
                defaults=cat_data,
            )
            if created:
                total_categories += 1
                self.stdout.write(f'  Created category: {category.icon} {category.name}')
            else:
                self.stdout.write(f'  Category exists: {category.icon} {category.name}')

            for prompt_data in prompts_data:
                _, p_created = Prompt.objects.get_or_create(
                    title=prompt_data['title'],
                    category=category,
                    defaults={
                        'title_ar': prompt_data.get('title_ar', ''),
                        'difficulty': prompt_data.get('difficulty', 3),
                    },
                )
                if p_created:
                    total_prompts += 1

            cat_data['prompts'] = prompts_data

        self.stdout.write(self.style.SUCCESS(
            f'\nSeeding complete: {total_categories} categories, {total_prompts} prompts created.'
        ))
